package types

import (
	"time"
)

// Side represents the outcome side in a binary market.
// For Polymarket Up/Down markets this can be mapped accordingly.
//
// IMPORTANT: This project treats markets as binary (YES/NO) at the execution layer.
// Higher-level naming (Up/Down) should be mapped in adapters.
type Side int

const (
	SideUnknown Side = iota
	SideYes
	SideNo
)

func (s Side) String() string {
	switch s {
	case SideYes:
		return "YES"
	case SideNo:
		return "NO"
	default:
		return "UNKNOWN"
	}
}

// EventType is a coarse-grained category for routing and auditing.
type EventType string

const (
	EventMarketSnapshot EventType = "market.snapshot"
	EventMarketTick     EventType = "market.tick"

	EventOrderUpdate EventType = "order.update"
	EventFill        EventType = "trade.fill"

	EventTimer EventType = "timer"
	EventRisk  EventType = "risk"
)

// Event is the only input into the single-threaded engine.
// All state changes must be derived from Events.
type Event struct {
	Type EventType

	// Seq is a monotonically increasing sequence generated by the local bus.
	Seq uint64

	// TsLocal is when the event was observed/created locally.
	TsLocal time.Time

	// TsExchange is the exchange-provided timestamp (if any).
	TsExchange time.Time

	// Key can be used for idempotency/deduplication for certain event classes.
	Key string

	Payload any
}

// MarketTick is a lightweight incremental update used for signals.
// pYes is expressed as a probability in [0,1].
// For binary markets pNo is implied (1-pYes).
type MarketTick struct {
	MarketID string

	PYes float64

	// Best bid/ask in probability-space (0..1). Optional.
	BestBid float64
	BestAsk float64

	TimeRemaining time.Duration

	// DataQuality is a 0..1 confidence score produced by adapters.
	DataQuality float64
}

// MarketSnapshot announces a new trading cycle/market context.
// Engine uses it as a hard boundary: reset per-cycle state (orders/positions/signals).
type MarketSnapshot struct {
	MarketID string
	MarketSlug string

	// CycleStart is derived from the slug timestamp when applicable.
	CycleStart time.Time
	EndDate    time.Time

	YesTokenID string
	NoTokenID  string

	MinTickSize  float64
	MinOrderSize float64
	NegRisk      bool
}

// Intent is the controller output.
// It expresses *intention* rather than concrete orders.
type Intent struct {
	MarketID string

	// BiasYes in [-1,1]. +1 means fully YES, -1 means fully NO.
	BiasYes float64

	// RiskDeltaMax is the maximum notional risk increase allowed this cycle.
	RiskDeltaMax float64

	// ModeMix in [0,1]. 1 means fully Normal, 0 means fully Shock.
	ModeMix float64

	Freeze bool

	Ts time.Time
}

// RiskState is produced by risk supervisors and consumed by the engine.
type RiskState struct {
	KillSwitch bool
	Freeze     bool

	Reason string
	Ts     time.Time
}
